language: go

sudo: false

os:
  - linux

services:
  - docker

before_script:
  - chmod u+x scripts/*

script:
  - scripts/bintest

before_deploy:
 - scripts/release
 - export BUILD_VERSION=`rake version`
 - sudo chmod -R 1777 releases
 - ls -la releases
 - ls -la releases/v$BUILD_VERSION

deploy:
 provider: releases
 api_key: "$GITHUB_OAUTH_TOKEN"
 file:
   - "releases/v$BUILD_VERSION/ski-$BUILD_VERSION-i386-apple-darwin14.tgz"
   - "releases/v$BUILD_VERSION/ski-$BUILD_VERSION-i686-pc-linux-gnu-glibc.tgz"
   - "releases/v$BUILD_VERSION/ski-$BUILD_VERSION-i686-w64-mingw32.tgz"
   - "releases/v$BUILD_VERSION/ski-$BUILD_VERSION-x86_64-apple-darwin14.tgz"
   - "releases/v$BUILD_VERSION/ski-$BUILD_VERSION-x86_64-pc-linux-gnu.tgz"
   - "releases/v$BUILD_VERSION/ski-$BUILD_VERSION-x86_64-pc-linux-busybox.tgz"
   - "releases/v$BUILD_VERSION/ski-$BUILD_VERSION-x86_64-w64-mingw32.tgz"
 skip_cleanup: true
 on:
   tags: true
   condition:
     - "$TRAVIS_OS_NAME == linux"

notifications:
  slack:
    secure: BY388FDEb3kwUbz9je1V4Wut939o73fZGBTgybbKh6uqiXCfZ/1JYqoCYCmdK7iqjl8aSTDTj3wNskW335Xa5zCYIQv0vbG/erJUQUffjXjIdLNvhJjwllkQmxm3CuI+L+HUzg63wkj/IOBO+WVxCdk2o/1z+xbjnVgkJM0VCTwUeEE85cHAelniO6ugVKsrvRq3n1rx7xfpRsheZb0OnDCONn9QunZMHMuNFvShXwawJJmEm28Ugdtsja2hUVW0zhnq2tC61vM7sfsqp3EVnDtrQOUIjzPCJT83/pvCEITHEYUhGdcs96tvrxjyq4i0hE34LYEgwYdmhbHSzhNx38x0wC9wn9cDIzM5/IXVV1l1ADOnY6EWbayJ9VrwNMuYkK6reY5qIhzTxQdxeFxx0pyQgLpl+RyuRTHUssU2feme30gQ+A4tSk0jbprF1wb+7EqMa6wzZeGQd80EE7wF81Hd2MxRBpTUGQyWtD3YpG7vOpVv58mwgjDMAzswdhMBpyAqF4bmpqQ+9uScjCxEf5SVRO/axvQWW1jbXux/MpIZ5w1SzVrzJu+dbBMZHVEyQ9RdEjotBJhK+MpWsDOhWwQfL25mYE9mMlrKfsY6moaLAWjpn8kQrAMl/lD3gWjVmDrYYgghBqtgf6lJtiB8k/T9La+RWovlZPVPe6oxxc4=
