language: go

sudo: false

os:
  - linux

services:
  - docker

before_script:
  - chmod u+x scripts/*

script:
  - go test ./src/...
  - gem install os
  - rake version
  - scripts/bintest

before_deploy:
  - scripts/release
  - gem install os
  - rake version
  - export BUILD_VERSION=`rake version`
  - echo $BUILD_VERSION
  - ls releases
  - sudo chmod -R 1777 releases
  - ls -la releases
  - cd releases
  - ls -la
  - echo "v$BUILD_VERSION"
  - echo "v${BUILD_VERSION}"
  - cd "v$BUILD_VERSION"
  - ls -ls

deploy:
  provider: releases
  api_key:
    secure: qG3uLTDt/NDgvNj4cqnyThw1sT37HVvq+SkAGwE9cY2lGorw7xUr8ChHNdfuekvgPf4b8nPNlmMxTc5T/g7omelGQgTjcYk/eViRuWCAYgsXAO9AtIbVp9m+vw/bC08hOUcziVV7MEk/k2pdu9ODQurwIeZrbVItkB41pFBtVZCyIPWG06flzRVhRgxmgrfG+6Gc0KO+bEH9dIHFDuBYk39gLfwhaMJEZsvCOpwpJFhqs7X29dP9UOS8yyeK5J1TF+0bLN/19clZZi8ZEwZcVzlO798J5nC6rKT27xa9V4/6mdJ5LQn+R4KBlCsMKum8QlsgUZPvskyl1PA8b++QcENbk4ZxR1/nBBkpFwgs/96OE9IAexZY1YTYLYSt5PzImuwq2F1BaZsZJ77iVndS8yleVI/tv11mVGaIBZiEoucdhAO15MBz8okgxzHl4/9fdpnhSLj4RWux7gp72qSNwnlXQl8p+tGerSY4JQzXl0vacnpBaX+jzFLeMQZQ5smCWKTW2Q2LRO2gPmqYT/h0+qqJEw1EOpHucsmrcRpPAJcY/DhTnDkW+ikvuqLq8y9Zm2TUCTkBSKGF4ywPTy9TF5XSuFq0pjKGN6ziXRNzoTchH7SnfEQQqwi4Y246luUCZBA8TawWnO/TRad0g47Zj0WT13gy+Q/oVg2mIrDz9b4=
  file:
    - "releases/$BUILD_VERSION/alpinepass-v$BUILD_VERSION-i386-apple-darwin14.tgz"
    - "releases/$BUILD_VERSION/alpinepass-v$BUILD_VERSION-i686-pc-linux-gnu-glibc.tgz"
    - "releases/$BUILD_VERSION/alpinepass-v$BUILD_VERSION-i686-w64-mingw32.tgz"
    - "releases/$BUILD_VERSION/alpinepass-v$BUILD_VERSION-x86_64-apple-darwin14.tgz"
    - "releases/$BUILD_VERSION/alpinepass-v$BUILD_VERSION-x86_64-pc-linux-gnu.tgz"
    - "releases/$BUILD_VERSION/alpinepass-v$BUILD_VERSION-x86_64-pc-linux-busybox.tgz"
    - "releases/$BUILD_VERSION/alpinepass-v$BUILD_VERSION-x86_64-w64-mingw32.tgz"
  skip_cleanup: true
  on:
    tags: true
    condition:
      - "$TRAVIS_OS_NAME == linux"

#    repo: appPlant/alpinepass

notifications:
  slack:
    secure: BY388FDEb3kwUbz9je1V4Wut939o73fZGBTgybbKh6uqiXCfZ/1JYqoCYCmdK7iqjl8aSTDTj3wNskW335Xa5zCYIQv0vbG/erJUQUffjXjIdLNvhJjwllkQmxm3CuI+L+HUzg63wkj/IOBO+WVxCdk2o/1z+xbjnVgkJM0VCTwUeEE85cHAelniO6ugVKsrvRq3n1rx7xfpRsheZb0OnDCONn9QunZMHMuNFvShXwawJJmEm28Ugdtsja2hUVW0zhnq2tC61vM7sfsqp3EVnDtrQOUIjzPCJT83/pvCEITHEYUhGdcs96tvrxjyq4i0hE34LYEgwYdmhbHSzhNx38x0wC9wn9cDIzM5/IXVV1l1ADOnY6EWbayJ9VrwNMuYkK6reY5qIhzTxQdxeFxx0pyQgLpl+RyuRTHUssU2feme30gQ+A4tSk0jbprF1wb+7EqMa6wzZeGQd80EE7wF81Hd2MxRBpTUGQyWtD3YpG7vOpVv58mwgjDMAzswdhMBpyAqF4bmpqQ+9uScjCxEf5SVRO/axvQWW1jbXux/MpIZ5w1SzVrzJu+dbBMZHVEyQ9RdEjotBJhK+MpWsDOhWwQfL25mYE9mMlrKfsY6moaLAWjpn8kQrAMl/lD3gWjVmDrYYgghBqtgf6lJtiB8k/T9La+RWovlZPVPe6oxxc4=
