version: '1.4.2.{build}'

clone_folder: c:\GoDev\src\github.com\appplant\alpinepass

environment:
  GOPATH: c:\GoDev

install:
  - cd src
  - go get github.com/urfave/cli
  - go get github.com/fatih/structs
  - go get gopkg.in/yaml.v2
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/assert

build_script:
  - go version
  - go env
  - go build -o alpinepass

test_script:
  - go test ./...
